// These functions exists as raw js functions in order to test the wrapping
// of javascript async functions that can result in errors

module.exports = {
  asyncSucceedingFunction: function(i, cb) {
    setTimeout(() => cb(null, i));
  },
  asyncThrowingFunction: function(i, cb) {
    setTimeout(() => cb(new Error("dummy"), null));
  }
};
